name: common
description: 基本组件.
version: 0.0.1
#author: xy
homepage: https://flutter.dev/
publish_to: http://192.168.20.141:8080

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # http 请求库
  dio: ^5.3.3
  # cookie
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.0+1
  # 格式化时间
  date_format: ^2.0.7
  # 本地存储
  shared_preferences: 2.2.2
  # 动态权限
  permission_handler: 11.0.1
  # RSA加密
  encrypt: 5.0.3

  # 选择图片
#  image_picker: 1.0.4
  # WebView
#  webview_flutter: 4.2.4
  # 图表
  flutter_echarts: ^2.5.0
  # 刷新
  flutter_easyrefresh: ^2.1.8
  flutter_cupertino_datetime_picker: 3.0.0
  # 时间选择器 该分支支持SDK1.20
#  flutter_cupertino_date_picker:
#    git:
#      url: https://github.com/arbyazra123/flutter-cupertino-date-picker.git
#      ref: updatedDiagnosticable


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - packages/common/widget/multiplestatus/status_widget/images/status_error.png
    - packages/common/widget/multiplestatus/status_widget/images/status_no_data.png
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
